### ISSUE TITLE
installation guide incomplete

### ISSUE THREAD

**Issue by kmahyyg** [nowsecure/dirtycow#3]
1. please add more details about the usage of cowpy
2. please notice users to run
   
   ```
   apt install radare2 radare2-dev -y
   apt install make make-dev clang pkg-config -y
   
   ```
   
   first to install the dependency in order to compile files correctly.

**Comment by manageryzy** [comment]
radare2-dev make-dev is not found on ubuntu 16.04

**Comment by trufae** [comment]
ubuntu have a 5 year old radare, those instructions are for termux. use sid or install r2 from git or use any other distro that cares about updating their software
