### ISSUE TITLE
Cowpy issue

### ISSUE THREAD

**Issue by HemanthJabalpuri** [nowsecure/dirtycow#8]
Sir I successfully changed the prop value in /system/build.prop with cowpy..
But after reboot it resets to the original value....

**Comment by trufae** [comment]
That’s exactly how dirtycow is suposed to work.

**Comment by HemanthJabalpuri** [comment]
@trufae
in build.sh, I think it is `if ! [ -d $T ]; then`...
there should be not (!) right?

**Comment by trufae** [comment]
This path only exists in termux. And thats where the script is suposed to run. So the conditional is correct. For other platforms use the makefile

**Comment by HemanthJabalpuri** [comment]
> This path only exists in termux. And thats where the script is suposed to run. So the conditional is correct. For other platforms use the makefile
> […](#)
> On 11 May 2019, at 13:05, HemanthJabalpuri ***@***.***> wrote: @trufae in build.sh, I think it is if ! [ -d $T ]; then... there should be not (!) right? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

If there is no NOT(!) then it will exit in Termux.... according to my basic scripting...

**Comment by trufae** [comment]
fixed it, yes you are right

**Comment by HemanthJabalpuri** [comment]
Sir @trufae
I made a wrapper script for cowpy to correctly overwriting file which is less in size than destination file...

[cowpy.sh.txt](https://github.com/nowsecure/dirtycow/files/3169711/cowpy.sh.txt)

**Comment by trufae** [comment]
Can you submit it in a PR to review the changes?

**Comment by HemanthJabalpuri** [comment]
> Can you submit it in a PR to review the changes?

Done.
